name: To work on github first project 
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: vinodhrunner
    strategy:
      matrix:
        python-version: [3.8,3.9]
    steps:
    - name: checkout source code
      uses: actions/checkout@v3
    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Run tests
      run: |
        cd src
        python addition.py
